- name: k8s-cp
  hosts: k8s_cp
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  tasks:
    - import_tasks : ./tasks/common.yml
    - import_tasks : ./tasks/k8s-cp.yml

- name: k8s-wk
  hosts: k8s_wk
  gather_facts: no
  user: user
  become: yes
  max_fail_percentage: 0
  tasks:
    - import_tasks : ./tasks/common.yml
    - import_tasks : ./tasks/k8s-wk.yml